---
services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:7.1.1
    container_name: zookeeper1
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2889:3889;zookeeper3:2890:3890
    volumes:
      - ./zookeeperDir/zookeeper1/data:/var/lib/zookeeper/data
      - ./zookeeperDir/zookeeper1/log:/var/lib/zookeeper/log

  zookeeper2:
    image: confluentinc/cp-zookeeper:7.1.1
    container_name: zookeeper2
    ports:
      - 2182:2182
      - 2889:2889
      - 3889:3889
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2889:3889;zookeeper3:2890:3890
    volumes:
      - ./zookeeperDir/zookeeper2/data:/var/lib/zookeeper/data
      - ./zookeeperDir/zookeeper2/log:/var/lib/zookeeper/log

  zookeeper3:
    image: confluentinc/cp-zookeeper:7.1.1
    container_name: zookeeper3
    ports:
      - 2183:2183
      - 2890:2890
      - 3890:3890
    environment:
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2889:3889;zookeeper3:2890:3890
    volumes:
      - ./zookeeperDir/zookeeper3/data:/var/lib/zookeeper/data
      - ./zookeeperDir/zookeeper3/log:/var/lib/zookeeper/log
